# Jekyll theme
remote_theme: open-and-sustainable/greendoc_theme
# title and description, URLs
title: "alembica"
description: "Documentation of `alembica`"
baseurl: "/alembica"
url: "https://open-and-sustainable.github.io"
github_repo: "https://github.com/open-and-sustainable/alembica"
# logo and favicon
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
# configuration of navigation entries
nav_links:
    - name: "/Users/Main Features"
      url: "/main-features.html"
    - name: "/Users/Getting Started"
      url: "/getting-started.html"
    - name: "/Users/Supported Models"
      url: "/supported-models.html"
    - name: "/Users/Rate Limits"
      url: "/rate-limits.html"
    - name: "/Users/Help & Resources"
      url: "/help-resources.html"
    - name: "/Integrators/Schemas & Validation"
      url: "/schemas-validation.html"
    - name: "/Integrators/MCP Server"
      url: "/mcp-server.html"
    - name: "/Integrators/C-Shared Library"
      url: "/cshared-library.html"
    - name: "/Contributors/Development"
      url: "/development.html"
    - name: "/Contributors/Research & Development"
      url: "/research-development.html"
# configuration of custom colors
nav_background_color: "#8B0000" # Dark Red (Maroon) for the nav bar
nav_hover_color: "#006400" # Dark Green for hover effects
nav_link_color: "#ffffff" # Keep white for readability
toc-hover-color: "#006400" # Dark Green for TOC hover color
