name: Build and Deploy Shared Libraries  

on:  
  release:  
    types: [created]  # Runs when a new release is published  

permissions:  
  contents: read  # Default to read-only permissions  

jobs:
  build-linux-amd64:
    name: Build Linux AMD64 Shared Library
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for uploading release assets
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'
      - name: Build shared library for Linux AMD64
        working-directory: utils/sharedlib
        run: |
          go mod tidy
          go build -buildmode=c-shared -o alembica_linux_amd64.so export.go
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: utils/sharedlib/alembica_linux_amd64.so

  build-linux-arm64:
    name: Build Linux ARM64 Shared Library
    runs-on: ubuntu-22.04-arm
    permissions:
      contents: write  # Needed for uploading release assets
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'
      - name: Build shared library for Linux ARM64
        working-directory: utils/sharedlib
        run: |
          go mod tidy
          go build -buildmode=c-shared -o alembica_linux_arm64.so export.go
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: utils/sharedlib/alembica_linux_arm64.so

  build-windows-amd64:
    name: Build Windows AMD64 Shared Library
    runs-on: windows-latest
    permissions:
      contents: write  # Needed for uploading release assets
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'
      - name: Build shared library for Windows AMD64
        working-directory: utils/sharedlib
        shell: pwsh
        run: |
          go mod tidy
          go build -buildmode=c-shared -o alembica_windows_amd64.dll export.go
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: utils/sharedlib/alembica_windows_amd64.dll

  build-macos-amd64:
    name: Build macOS AMD64 Shared Library
    runs-on: macos-13
    permissions:
      contents: write  # Needed for uploading release assets
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'
      - name: Build shared library for macOS AMD64
        working-directory: utils/sharedlib
        run: |
          go mod tidy
          go build -buildmode=c-shared -o alembica_darwin_amd64.dylib export.go
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: utils/sharedlib/alembica_darwin_amd64.dylib

  build-macos-arm64:
    name: Build macOS ARM64 Shared Library
    runs-on: macos-latest
    permissions:
      contents: write  # Needed for uploading release assets
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'
      - name: Build shared library for macOS ARM64
        working-directory: utils/sharedlib
        run: |
          go mod tidy
          go build -buildmode=c-shared -o alembica_darwin_arm64.dylib export.go
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: utils/sharedlib/alembica_darwin_arm64.dylib
