name: Build and Deploy Shared Libraries  

on:  
  workflow_dispatch:  

jobs:
  build-linux:
    name: Build Linux Shared Library
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'

      - name: Build shared library for Linux
        working-directory: utils/sharedlib
        run: |
          GOOS=linux GOARCH=${{ matrix.arch }} go build -buildmode=c-shared -o libprismaid_linux_${{ matrix.arch }}.so export.go

      - name: Upload Linux shared library artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.arch }}-shared-library
          path: utils/sharedlib/libprismaid_linux_${{ matrix.arch }}.so

  build-windows:
    name: Build Windows Shared Library
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.PAT_TOKEN }}

    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build shared library for Windows
        working-directory: sharedlib
        shell: pwsh
        run: |
          $Env:GOOS="windows"
          $Env:GOARCH="${{ matrix.arch }}"
          go build -buildmode=c-shared -o libprismaid_windows_${{ matrix.arch }}.dll .\export.go

      - name: Upload Windows shared library artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-${{ matrix.arch }}-shared-library
          path: sharedlib/libprismaid_windows_${{ matrix.arch }}.dll

  build-macos:
    name: Build macOS Shared Library
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.PAT_TOKEN }}

    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build shared library for macOS
        working-directory: sharedlib
        run: |
          GOOS=darwin GOARCH=${{ matrix.arch }} go build -buildmode=c-shared -o libprismaid_darwin_${{ matrix.arch }}.dylib export.go

      - name: Upload macOS shared library artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{ matrix.arch }}-shared-library
          path: sharedlib/libprismaid_darwin_${{ matrix.arch }}.dylib

          